### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by eriktelepovsky** [zostera/django-modeltrans#94]
Hello:

``def _filter_or_exclude(self, negate, args, kwargs)`` sometimes generates None query which causes TypeError. Any ideas why and how to fix it please?

```
Traceback (most recent call last):
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1697, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/contrib/admin/options.py", line 736, in get_changelist_instance
    return ChangeList(
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/contrib/admin/views/main.py", line 488, in get_queryset
    qs = self.root_queryset.filter(Exists(qs))
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/modeltrans/manager.py", line 300, in _filter_or_exclude
    return super()._filter_or_exclude(negate, new_args, new_kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1265, in build_filter
    return self._add_q(
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/erik/env/eskills/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1283, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable NoneType object
```

Output of negate, new_args and new_kwargs in ``modeltrans.manager._filter_or_exclude``:

```
False [] {'sites__id__exact': '1'}
False [] {}
False [] {}
False [] {'pk': OuterRef(pk)}
False [<Q: (AND: None)>] {}
```

**Comment by browniebroke** [comment]
I've hit this issue as well, in my case it happens if a translated model makes use of [`limit_choices-to`](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.ForeignKey.limit_choices_to) in a foreign key.

I've added a test case that reproduces the problem in #100. I'll try to see if I can make a fix.

**Comment by browniebroke** [comment]
[The fix](https://github.com/browniebroke/django-modeltrans/commit/b0827f8784d18cf12603c02150a84e1693c94c08) was pretty simple. I've been using my fork in prod for some time now, seems to work fine.
